# Generated by Django 4.1.4 on 2022-12-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20190318_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('net_price', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=90)),
                ('phone', models.CharField(default='', max_length=111)),
                ('email', models.CharField(max_length=111)),
                ('address', models.CharField(max_length=111)),
                ('city', models.CharField(max_length=111)),
                ('state', models.CharField(max_length=111)),
                ('zip_code', models.CharField(max_length=111)),
            ],
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Live_Show'},
        ),
        migrations.AddField(
            model_name='booking',
            name='net_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.FileField(upload_to='home/live_show/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name=' Shwo name'),
        ),
    ]
