# Generated by Django 4.1.4 on 2022-12-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_checkout_alter_event_options_booking_net_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='email',
            field=models.EmailField(max_length=111),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='phone',
            field=models.IntegerField(default='', max_length=111),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='zip_code',
            field=models.IntegerField(max_length=111),
        ),
    ]
