# Generated by Django 4.1.4 on 2022-12-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_checkout_email_alter_checkout_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='address',
            field=models.CharField(default='', max_length=111),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='city',
            field=models.CharField(default='', max_length=111),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='email',
            field=models.EmailField(default='', max_length=111),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='name',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='phone',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='state',
            field=models.CharField(default='', max_length=111),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='zip_code',
            field=models.IntegerField(default=0, max_length=111),
        ),
    ]
