# Generated by Django 4.1.4 on 2022-12-30 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_checkout_address_alter_checkout_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='net_price',
        ),
    ]
